include_guard(DIRECTORY)

function(append_flags_if_missing VAR_NAME FLAGS_STR DOC_STRING)
    if ("${FLAGS_STR}" STREQUAL "")
        return()
    endif ()
    if (DEFINED CACHE{${VAR_NAME}})
        set(_current "${${VAR_NAME}}")
    else ()
        set(_current "")
    endif ()
    string(REGEX REPLACE "([][+.*()^$\\\\])" "\\\\\\1" _flags_escaped "${FLAGS_STR}")
    if (NOT _current MATCHES "${_flags_escaped}")
        set(${VAR_NAME} "${_current} ${FLAGS_STR}" CACHE STRING "${DOC_STRING}" FORCE)
    endif ()
endfunction()
