when:
  - event: [pull_request]
    branch: [main, dev]

steps:
  # Linux / Clang - x86_x64
  - name: build-linux-x86_x64-clang-debug
    image: dockcross/linux-x64-clang
    environment:
      CONFIG_PRESET: unixlike-clang-debug
    commands:
      - cmake -S . --preset unixlike-x64-clang-debug
    when:
    - event: [pull_request]
      branch: [main, dev]

  # Linux / Clang - x86
  - name: build-linux-x86-clang-debug
    image: dockcross/linux-x64-clang
    environment:
      CONFIG_PRESET: unixlike-clang-debug
    commands:
      - cmake -S . --preset unixlike-x86-clang-debug
    when:
    - event: [pull_request]
      branch: [main, dev]

  # Linux / GCC - x86_x64
  - name: build-linux-x86_x64-gcc-debug
    image: dockcross/linux-x86_64-full
    environment:
      CONFIG_PRESET: unixlike-gcc-debug
    commands:
      - cmake -S . --preset unixlike-x64-gcc-debug
    when:
    - event: [pull_request]
      branch: [main, dev]

  # Linux / GCC - x86
  - name: build-linux-x86-gcc-debug
    image: dockcross/linux-x86_64-full
    environment:
      CONFIG_PRESET: unixlike-gcc-debug
    commands:
      - cmake -S . --preset unixlike-x86-gcc-debug
    when:
    - event: [pull_request]
      branch: [main, dev]

  # Emscripten
  - name: build-emscripten-debug
    image: dockcross/web-wasm
    commands:
      - cmake -S . --preset emscripten-debug
    when:
    - event: [pull_request]
      branch: [main, dev]
