when:
  - event: [pull_request]
    branch: [main, dev]

steps:
  # Linux / Clang
  - name: build-linux-x64-clang-debug
    image: ubuntu:latest
    commands:
      - chmod +x .woodpecker/scripts/test/setup-unix.sh
      - .woodpecker/scripts/test/setup-unix.sh
      - cmake -S . -B ./out/build/build-linux-x64-clang-debug --preset unixlike-clang-debug
    when:
    - event: [pull_request]
      branch: [main, dev]

  # Linux / GCC
  - name: build-linux-x64-gcc-debug
    image: ubuntu:latest
    commands:
      - chmod +x .woodpecker/scripts/test/setup-unix.sh
      - .woodpecker/scripts/test/setup-unix.sh
      - cmake -S . -B ./out/build/build-linux-x64-gcc-debug --preset unixlike-gcc-debug
    when:
    - event: [pull_request]
      branch: [main, dev]

  # Emscripten
  - name: build-emscripten-debug
    image: emscripten/emsdk:latest
    commands:
      - chmod +x .woodpecker/scripts/test/setup-emscripten.sh
      - .woodpecker/scripts/test/setup-emscripten.sh
      - cmake -S . -B ./out/build/build-emscripten-debug --preset emscripten-debug
    when:
    - event: [pull_request]
      branch: [main, dev]
