when:
  - event: [pull_request]
    branch: [main, dev]

steps:
  # Linux / Clang
  - name: build-linux-x64-clang-debug
    image: dockcross/linux-x64-clang
    environment:
      CONFIG_PRESET: unixlike-clang-debug
    commands:
      - cmake -S . -B ./out/build/build-linux-x64-clang-debug --preset unixlike-clang-debug
    when:
    - event: [pull_request]
      branch: [main, dev]

  # Linux / GCC
  - name: build-linux-x64-gcc-debug
    image: dockcross/linux-x86_64-full
    environment:
      CONFIG_PRESET: unixlike-gcc-debug
    commands:
      - cmake -S . -B ./out/build/build-linux-x64-gcc-debug --preset unixlike-gcc-debug
    when:
    - event: [pull_request]
      branch: [main, dev]

  # Emscripten
  - name: build-emscripten-debug
    image: dockcross/web-wasm
    commands:
      - chmod +x .woodpecker/scripts/test/setup-emscripten.sh
      - .woodpecker/scripts/test/setup-emscripten.sh
      - XMAKE_ROOT=y cmake -S . -B ./out/build/build-emscripten-debug --preset emscripten-debug
    when:
    - event: [pull_request]
      branch: [main, dev]
