when:
  - event: [push, pull_request]
    branch: [main, dev]
  - event: tag

steps:
  # # Linux / Clang
  # - name: test-linux-x64-clang
  #   image: ubuntu:latest
  #   environment:
  #     CONFIG_NAME: linux-x64-clang
  #     CONFIG_OS: ubuntu-latest
  #     CONFIG_PRESET: unixlike-clang-debug
  #     CONFIG_OUTPUT: linux-x64-clang
  #   commands:
  #     - chmod +x .woodpecker/scripts/test/unix.sh
  #     - .woodpecker/scripts/test/unix.sh
  #   when:
  #     event: [push, pull_request, tag]

  # # Linux / GCC
  # - name: test-linux-x64-gcc
  #   image: ubuntu:latest
  #   environment:
  #     CONFIG_NAME: linux-x64-gcc
  #     CONFIG_OS: ubuntu-latest
  #     CONFIG_PRESET: unixlike-gcc-debug
  #     CONFIG_OUTPUT: linux-x64-gcc
  #   commands:
  #     - chmod +x .woodpecker/scripts/test/unix.sh
  #     - .woodpecker/scripts/test/unix.sh
  #   when:
  #     event: [push, pull_request, tag]

  # Windows / Clang
  - name: test-windows-x64-clang
    image: mcr.microsoft.com/windows/servercore
    environment:
      CONFIG_NAME: windows-x64-clang
      CONFIG_OS: windows-latest
      CONFIG_PRESET: windows-clang-debug
      CONFIG_OUTPUT: windows-x64-clang
    commands:
      - powershell -NonInteractive -File .woodpecker/scripts/test/windows.ps1
    when:
      event: [push, pull_request, tag]

  # Windows / MSVC
  - name: test-windows-x64-msvc
    image: mcr.microsoft.com/windows/servercore
    environment:
      CONFIG_NAME: windows-x64-msvc
      CONFIG_OS: windows-latest
      CONFIG_PRESET: windows-msvc-debug
      CONFIG_OUTPUT: windows-x64-msvc
    commands:
      - powershell -NonInteractive -File .woodpecker/scripts/test/windows.ps1
    when:
      event: [push, pull_request, tag]

  # Emscripten
  - name: test-emscripten-debug
    image: emscripten/emsdk:latest
    environment:
      CONFIG_NAME: emscripten-debug
      CONFIG_OS: ubuntu-latest
      CONFIG_PRESET: emscripten-debug
      CONFIG_OUTPUT: wasm-debug
    commands:
      - chmod +x .woodpecker/scripts/test/emscripten.sh
      - .woodpecker/scripts/test/emscripten.sh
    when:
      event: [push, pull_request, tag]
