depends_on:
  - build
when:
  - event: [pull_request]
    branch: [main, dev]

steps:
  # Linux / Clang - x86_x64
  - name: test-linux-x86_x64-clang-debug
    image: dockcross/linux-x64-clang
    commands:
      - ctest --test-dir build/unixlike-x64-clang-debug --build-config Debug --output-on-failure
    depends_on:
      - build
    when:
      - event: [pull_request]
        branch: [main, dev]

  # Linux / Clang - x86
  - name: test-linux-x86-clang-debug
    image: dockcross/linux-x64-clang
    commands:
      - ctest --test-dir build/unixlike-x86-clang-debug --build-config Debug --output-on-failure
    depends_on:
      - build
    when:
      - event: [pull_request]
        branch: [main, dev]

  # Linux / GCC - x86_x64
  - name: test-linux-x86_x64-gcc-debug
    image: dockcross/linux-x86_64-full
    commands:
      - ctest --test-dir build/unixlike-x64-gcc-debug --build-config Debug --output-on-failure
    depends_on:
      - build
    when:
      - event: [pull_request]
        branch: [main, dev]

  # Linux / GCC - x86
  - name: test-linux-x86-gcc-debug
    image: dockcross/linux-x86
    commands:
      - ctest --test-dir build/unixlike-x86-gcc-debug --build-config Debug --output-on-failure
    depends_on:
      - build
    when:
      - event: [pull_request]
        branch: [main, dev]